/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplySlugRouteImport } from './routes/apply.$slug'
import { Route as AuthenticatedTalentportalRouteImport } from './routes/_authenticated.talentportal'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated.staff'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated.portal'
import { Route as AuthenticatedMainRouteImport } from './routes/_authenticated.main'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated.jobs'
import { Route as AuthenticatedClientRouteImport } from './routes/_authenticated/client'
import { Route as AuthenticatedTalentportalIndexRouteImport } from './routes/_authenticated.talentportal.index'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated.staff.index'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated.portal.index'
import { Route as AuthenticatedMainIndexRouteImport } from './routes/_authenticated.main.index'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated.jobs.index'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client.index'
import { Route as AuthenticatedTalentportalStaffRouteImport } from './routes/_authenticated.talentportal.staff'
import { Route as AuthenticatedTalentportalMainRouteImport } from './routes/_authenticated.talentportal.main'
import { Route as AuthenticatedTalentportalClientsRouteImport } from './routes/_authenticated.talentportal.clients'
import { Route as AuthenticatedStaffShortlistRouteImport } from './routes/_authenticated.staff.shortlist'
import { Route as AuthenticatedStaffCandidatesRouteImport } from './routes/_authenticated.staff.candidates'
import { Route as AuthenticatedStaffActivityRouteImport } from './routes/_authenticated.staff.activity'
import { Route as AuthenticatedStaffIdRouteImport } from './routes/_authenticated.staff.$id'
import { Route as AuthenticatedPortalSplatRouteImport } from './routes/_authenticated.portal.$'
import { Route as AuthenticatedMainSettingsRouteImport } from './routes/_authenticated.main.settings'
import { Route as AuthenticatedMainClientsRouteImport } from './routes/_authenticated.main.clients'
import { Route as AuthenticatedMainAdminRouteImport } from './routes/_authenticated.main.admin'
import { Route as AuthenticatedJobsSlugRouteImport } from './routes/_authenticated.jobs.$slug'
import { Route as AuthenticatedStaffJobsIndexRouteImport } from './routes/_authenticated.staff.jobs.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedStaffJobsSlugRouteImport } from './routes/_authenticated.staff.jobs.$slug'
import { Route as AuthenticatedMainJobsNewRouteImport } from './routes/_authenticated.main.jobs.new'
import { Route as AuthenticatedMainClientsIdRouteImport } from './routes/_authenticated.main.clients.$id'
import { Route as AuthenticatedJobsSlugStagesRouteImport } from './routes/_authenticated.jobs.$slug.stages'
import { Route as AuthenticatedJobsSlugAddCandidateRouteImport } from './routes/_authenticated.jobs.$slug.add-candidate'
import { Route as AuthenticatedClientJobsSlugRouteImport } from './routes/_authenticated/client.jobs.$slug'
import { Route as AuthenticatedStaffJobsSlugStagesRouteImport } from './routes/_authenticated.staff.jobs.$slug.stages'
import { Route as AuthenticatedStaffJobsSlugAddCandidateRouteImport } from './routes/_authenticated.staff.jobs.$slug.add-candidate'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplySlugRoute = ApplySlugRouteImport.update({
  id: '/apply/$slug',
  path: '/apply/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTalentportalRoute =
  AuthenticatedTalentportalRouteImport.update({
    id: '/talentportal',
    path: '/talentportal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMainRoute = AuthenticatedMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientRoute = AuthenticatedClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTalentportalIndexRoute =
  AuthenticatedTalentportalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTalentportalRoute,
  } as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedMainIndexRoute = AuthenticatedMainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMainRoute,
} as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedJobsRoute,
} as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedTalentportalStaffRoute =
  AuthenticatedTalentportalStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedTalentportalRoute,
  } as any)
const AuthenticatedTalentportalMainRoute =
  AuthenticatedTalentportalMainRouteImport.update({
    id: '/main',
    path: '/main',
    getParentRoute: () => AuthenticatedTalentportalRoute,
  } as any)
const AuthenticatedTalentportalClientsRoute =
  AuthenticatedTalentportalClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedTalentportalRoute,
  } as any)
const AuthenticatedStaffShortlistRoute =
  AuthenticatedStaffShortlistRouteImport.update({
    id: '/shortlist',
    path: '/shortlist',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffCandidatesRoute =
  AuthenticatedStaffCandidatesRouteImport.update({
    id: '/candidates',
    path: '/candidates',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffActivityRoute =
  AuthenticatedStaffActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffIdRoute = AuthenticatedStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedPortalSplatRoute =
  AuthenticatedPortalSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedMainSettingsRoute =
  AuthenticatedMainSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedMainRoute,
  } as any)
const AuthenticatedMainClientsRoute =
  AuthenticatedMainClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedMainRoute,
  } as any)
const AuthenticatedMainAdminRoute = AuthenticatedMainAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedMainRoute,
} as any)
const AuthenticatedJobsSlugRoute = AuthenticatedJobsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedJobsRoute,
} as any)
const AuthenticatedStaffJobsIndexRoute =
  AuthenticatedStaffJobsIndexRouteImport.update({
    id: '/jobs/',
    path: '/jobs/',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffJobsSlugRoute =
  AuthenticatedStaffJobsSlugRouteImport.update({
    id: '/jobs/$slug',
    path: '/jobs/$slug',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedMainJobsNewRoute =
  AuthenticatedMainJobsNewRouteImport.update({
    id: '/jobs/new',
    path: '/jobs/new',
    getParentRoute: () => AuthenticatedMainRoute,
  } as any)
const AuthenticatedMainClientsIdRoute =
  AuthenticatedMainClientsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMainClientsRoute,
  } as any)
const AuthenticatedJobsSlugStagesRoute =
  AuthenticatedJobsSlugStagesRouteImport.update({
    id: '/stages',
    path: '/stages',
    getParentRoute: () => AuthenticatedJobsSlugRoute,
  } as any)
const AuthenticatedJobsSlugAddCandidateRoute =
  AuthenticatedJobsSlugAddCandidateRouteImport.update({
    id: '/add-candidate',
    path: '/add-candidate',
    getParentRoute: () => AuthenticatedJobsSlugRoute,
  } as any)
const AuthenticatedClientJobsSlugRoute =
  AuthenticatedClientJobsSlugRouteImport.update({
    id: '/jobs/$slug',
    path: '/jobs/$slug',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedStaffJobsSlugStagesRoute =
  AuthenticatedStaffJobsSlugStagesRouteImport.update({
    id: '/stages',
    path: '/stages',
    getParentRoute: () => AuthenticatedStaffJobsSlugRoute,
  } as any)
const AuthenticatedStaffJobsSlugAddCandidateRoute =
  AuthenticatedStaffJobsSlugAddCandidateRouteImport.update({
    id: '/add-candidate',
    path: '/add-candidate',
    getParentRoute: () => AuthenticatedStaffJobsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/client': typeof AuthenticatedClientRouteWithChildren
  '/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/main': typeof AuthenticatedMainRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/talentportal': typeof AuthenticatedTalentportalRouteWithChildren
  '/apply/$slug': typeof ApplySlugRoute
  '/jobs/$slug': typeof AuthenticatedJobsSlugRouteWithChildren
  '/main/admin': typeof AuthenticatedMainAdminRoute
  '/main/clients': typeof AuthenticatedMainClientsRouteWithChildren
  '/main/settings': typeof AuthenticatedMainSettingsRoute
  '/portal/$': typeof AuthenticatedPortalSplatRoute
  '/staff/$id': typeof AuthenticatedStaffIdRoute
  '/staff/activity': typeof AuthenticatedStaffActivityRoute
  '/staff/candidates': typeof AuthenticatedStaffCandidatesRoute
  '/staff/shortlist': typeof AuthenticatedStaffShortlistRoute
  '/talentportal/clients': typeof AuthenticatedTalentportalClientsRoute
  '/talentportal/main': typeof AuthenticatedTalentportalMainRoute
  '/talentportal/staff': typeof AuthenticatedTalentportalStaffRoute
  '/client/': typeof AuthenticatedClientIndexRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/main/': typeof AuthenticatedMainIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/talentportal/': typeof AuthenticatedTalentportalIndexRoute
  '/client/jobs/$slug': typeof AuthenticatedClientJobsSlugRoute
  '/jobs/$slug/add-candidate': typeof AuthenticatedJobsSlugAddCandidateRoute
  '/jobs/$slug/stages': typeof AuthenticatedJobsSlugStagesRoute
  '/main/clients/$id': typeof AuthenticatedMainClientsIdRoute
  '/main/jobs/new': typeof AuthenticatedMainJobsNewRoute
  '/staff/jobs/$slug': typeof AuthenticatedStaffJobsSlugRouteWithChildren
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/staff/jobs/': typeof AuthenticatedStaffJobsIndexRoute
  '/staff/jobs/$slug/add-candidate': typeof AuthenticatedStaffJobsSlugAddCandidateRoute
  '/staff/jobs/$slug/stages': typeof AuthenticatedStaffJobsSlugStagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/jobs/$slug': typeof AuthenticatedJobsSlugRouteWithChildren
  '/main/admin': typeof AuthenticatedMainAdminRoute
  '/main/clients': typeof AuthenticatedMainClientsRouteWithChildren
  '/main/settings': typeof AuthenticatedMainSettingsRoute
  '/portal/$': typeof AuthenticatedPortalSplatRoute
  '/staff/$id': typeof AuthenticatedStaffIdRoute
  '/staff/activity': typeof AuthenticatedStaffActivityRoute
  '/staff/candidates': typeof AuthenticatedStaffCandidatesRoute
  '/staff/shortlist': typeof AuthenticatedStaffShortlistRoute
  '/talentportal/clients': typeof AuthenticatedTalentportalClientsRoute
  '/talentportal/main': typeof AuthenticatedTalentportalMainRoute
  '/talentportal/staff': typeof AuthenticatedTalentportalStaffRoute
  '/client': typeof AuthenticatedClientIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/main': typeof AuthenticatedMainIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/talentportal': typeof AuthenticatedTalentportalIndexRoute
  '/client/jobs/$slug': typeof AuthenticatedClientJobsSlugRoute
  '/jobs/$slug/add-candidate': typeof AuthenticatedJobsSlugAddCandidateRoute
  '/jobs/$slug/stages': typeof AuthenticatedJobsSlugStagesRoute
  '/main/clients/$id': typeof AuthenticatedMainClientsIdRoute
  '/main/jobs/new': typeof AuthenticatedMainJobsNewRoute
  '/staff/jobs/$slug': typeof AuthenticatedStaffJobsSlugRouteWithChildren
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/staff/jobs': typeof AuthenticatedStaffJobsIndexRoute
  '/staff/jobs/$slug/add-candidate': typeof AuthenticatedStaffJobsSlugAddCandidateRoute
  '/staff/jobs/$slug/stages': typeof AuthenticatedStaffJobsSlugStagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/client': typeof AuthenticatedClientRouteWithChildren
  '/_authenticated/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/_authenticated/main': typeof AuthenticatedMainRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/_authenticated/talentportal': typeof AuthenticatedTalentportalRouteWithChildren
  '/apply/$slug': typeof ApplySlugRoute
  '/_authenticated/jobs/$slug': typeof AuthenticatedJobsSlugRouteWithChildren
  '/_authenticated/main/admin': typeof AuthenticatedMainAdminRoute
  '/_authenticated/main/clients': typeof AuthenticatedMainClientsRouteWithChildren
  '/_authenticated/main/settings': typeof AuthenticatedMainSettingsRoute
  '/_authenticated/portal/$': typeof AuthenticatedPortalSplatRoute
  '/_authenticated/staff/$id': typeof AuthenticatedStaffIdRoute
  '/_authenticated/staff/activity': typeof AuthenticatedStaffActivityRoute
  '/_authenticated/staff/candidates': typeof AuthenticatedStaffCandidatesRoute
  '/_authenticated/staff/shortlist': typeof AuthenticatedStaffShortlistRoute
  '/_authenticated/talentportal/clients': typeof AuthenticatedTalentportalClientsRoute
  '/_authenticated/talentportal/main': typeof AuthenticatedTalentportalMainRoute
  '/_authenticated/talentportal/staff': typeof AuthenticatedTalentportalStaffRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/main/': typeof AuthenticatedMainIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/talentportal/': typeof AuthenticatedTalentportalIndexRoute
  '/_authenticated/client/jobs/$slug': typeof AuthenticatedClientJobsSlugRoute
  '/_authenticated/jobs/$slug/add-candidate': typeof AuthenticatedJobsSlugAddCandidateRoute
  '/_authenticated/jobs/$slug/stages': typeof AuthenticatedJobsSlugStagesRoute
  '/_authenticated/main/clients/$id': typeof AuthenticatedMainClientsIdRoute
  '/_authenticated/main/jobs/new': typeof AuthenticatedMainJobsNewRoute
  '/_authenticated/staff/jobs/$slug': typeof AuthenticatedStaffJobsSlugRouteWithChildren
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/staff/jobs/': typeof AuthenticatedStaffJobsIndexRoute
  '/_authenticated/staff/jobs/$slug/add-candidate': typeof AuthenticatedStaffJobsSlugAddCandidateRoute
  '/_authenticated/staff/jobs/$slug/stages': typeof AuthenticatedStaffJobsSlugStagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/unauthorized'
    | '/client'
    | '/jobs'
    | '/main'
    | '/portal'
    | '/staff'
    | '/talentportal'
    | '/apply/$slug'
    | '/jobs/$slug'
    | '/main/admin'
    | '/main/clients'
    | '/main/settings'
    | '/portal/$'
    | '/staff/$id'
    | '/staff/activity'
    | '/staff/candidates'
    | '/staff/shortlist'
    | '/talentportal/clients'
    | '/talentportal/main'
    | '/talentportal/staff'
    | '/client/'
    | '/jobs/'
    | '/main/'
    | '/portal/'
    | '/staff/'
    | '/talentportal/'
    | '/client/jobs/$slug'
    | '/jobs/$slug/add-candidate'
    | '/jobs/$slug/stages'
    | '/main/clients/$id'
    | '/main/jobs/new'
    | '/staff/jobs/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/staff/jobs/'
    | '/staff/jobs/$slug/add-candidate'
    | '/staff/jobs/$slug/stages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/unauthorized'
    | '/apply/$slug'
    | '/jobs/$slug'
    | '/main/admin'
    | '/main/clients'
    | '/main/settings'
    | '/portal/$'
    | '/staff/$id'
    | '/staff/activity'
    | '/staff/candidates'
    | '/staff/shortlist'
    | '/talentportal/clients'
    | '/talentportal/main'
    | '/talentportal/staff'
    | '/client'
    | '/jobs'
    | '/main'
    | '/portal'
    | '/staff'
    | '/talentportal'
    | '/client/jobs/$slug'
    | '/jobs/$slug/add-candidate'
    | '/jobs/$slug/stages'
    | '/main/clients/$id'
    | '/main/jobs/new'
    | '/staff/jobs/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/staff/jobs'
    | '/staff/jobs/$slug/add-candidate'
    | '/staff/jobs/$slug/stages'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/unauthorized'
    | '/_authenticated/client'
    | '/_authenticated/jobs'
    | '/_authenticated/main'
    | '/_authenticated/portal'
    | '/_authenticated/staff'
    | '/_authenticated/talentportal'
    | '/apply/$slug'
    | '/_authenticated/jobs/$slug'
    | '/_authenticated/main/admin'
    | '/_authenticated/main/clients'
    | '/_authenticated/main/settings'
    | '/_authenticated/portal/$'
    | '/_authenticated/staff/$id'
    | '/_authenticated/staff/activity'
    | '/_authenticated/staff/candidates'
    | '/_authenticated/staff/shortlist'
    | '/_authenticated/talentportal/clients'
    | '/_authenticated/talentportal/main'
    | '/_authenticated/talentportal/staff'
    | '/_authenticated/client/'
    | '/_authenticated/jobs/'
    | '/_authenticated/main/'
    | '/_authenticated/portal/'
    | '/_authenticated/staff/'
    | '/_authenticated/talentportal/'
    | '/_authenticated/client/jobs/$slug'
    | '/_authenticated/jobs/$slug/add-candidate'
    | '/_authenticated/jobs/$slug/stages'
    | '/_authenticated/main/clients/$id'
    | '/_authenticated/main/jobs/new'
    | '/_authenticated/staff/jobs/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/staff/jobs/'
    | '/_authenticated/staff/jobs/$slug/add-candidate'
    | '/_authenticated/staff/jobs/$slug/stages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApplySlugRoute: typeof ApplySlugRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$slug': {
      id: '/apply/$slug'
      path: '/apply/$slug'
      fullPath: '/apply/$slug'
      preLoaderRoute: typeof ApplySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/talentportal': {
      id: '/_authenticated/talentportal'
      path: '/talentportal'
      fullPath: '/talentportal'
      preLoaderRoute: typeof AuthenticatedTalentportalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/main': {
      id: '/_authenticated/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof AuthenticatedMainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client': {
      id: '/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AuthenticatedClientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/talentportal/': {
      id: '/_authenticated/talentportal/'
      path: '/'
      fullPath: '/talentportal/'
      preLoaderRoute: typeof AuthenticatedTalentportalIndexRouteImport
      parentRoute: typeof AuthenticatedTalentportalRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/main/': {
      id: '/_authenticated/main/'
      path: '/'
      fullPath: '/main/'
      preLoaderRoute: typeof AuthenticatedMainIndexRouteImport
      parentRoute: typeof AuthenticatedMainRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedJobsRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/talentportal/staff': {
      id: '/_authenticated/talentportal/staff'
      path: '/staff'
      fullPath: '/talentportal/staff'
      preLoaderRoute: typeof AuthenticatedTalentportalStaffRouteImport
      parentRoute: typeof AuthenticatedTalentportalRoute
    }
    '/_authenticated/talentportal/main': {
      id: '/_authenticated/talentportal/main'
      path: '/main'
      fullPath: '/talentportal/main'
      preLoaderRoute: typeof AuthenticatedTalentportalMainRouteImport
      parentRoute: typeof AuthenticatedTalentportalRoute
    }
    '/_authenticated/talentportal/clients': {
      id: '/_authenticated/talentportal/clients'
      path: '/clients'
      fullPath: '/talentportal/clients'
      preLoaderRoute: typeof AuthenticatedTalentportalClientsRouteImport
      parentRoute: typeof AuthenticatedTalentportalRoute
    }
    '/_authenticated/staff/shortlist': {
      id: '/_authenticated/staff/shortlist'
      path: '/shortlist'
      fullPath: '/staff/shortlist'
      preLoaderRoute: typeof AuthenticatedStaffShortlistRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/candidates': {
      id: '/_authenticated/staff/candidates'
      path: '/candidates'
      fullPath: '/staff/candidates'
      preLoaderRoute: typeof AuthenticatedStaffCandidatesRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/activity': {
      id: '/_authenticated/staff/activity'
      path: '/activity'
      fullPath: '/staff/activity'
      preLoaderRoute: typeof AuthenticatedStaffActivityRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/$id': {
      id: '/_authenticated/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof AuthenticatedStaffIdRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/portal/$': {
      id: '/_authenticated/portal/$'
      path: '/$'
      fullPath: '/portal/$'
      preLoaderRoute: typeof AuthenticatedPortalSplatRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/main/settings': {
      id: '/_authenticated/main/settings'
      path: '/settings'
      fullPath: '/main/settings'
      preLoaderRoute: typeof AuthenticatedMainSettingsRouteImport
      parentRoute: typeof AuthenticatedMainRoute
    }
    '/_authenticated/main/clients': {
      id: '/_authenticated/main/clients'
      path: '/clients'
      fullPath: '/main/clients'
      preLoaderRoute: typeof AuthenticatedMainClientsRouteImport
      parentRoute: typeof AuthenticatedMainRoute
    }
    '/_authenticated/main/admin': {
      id: '/_authenticated/main/admin'
      path: '/admin'
      fullPath: '/main/admin'
      preLoaderRoute: typeof AuthenticatedMainAdminRouteImport
      parentRoute: typeof AuthenticatedMainRoute
    }
    '/_authenticated/jobs/$slug': {
      id: '/_authenticated/jobs/$slug'
      path: '/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof AuthenticatedJobsSlugRouteImport
      parentRoute: typeof AuthenticatedJobsRoute
    }
    '/_authenticated/staff/jobs/': {
      id: '/_authenticated/staff/jobs/'
      path: '/jobs'
      fullPath: '/staff/jobs/'
      preLoaderRoute: typeof AuthenticatedStaffJobsIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff/jobs/$slug': {
      id: '/_authenticated/staff/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/staff/jobs/$slug'
      preLoaderRoute: typeof AuthenticatedStaffJobsSlugRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/main/jobs/new': {
      id: '/_authenticated/main/jobs/new'
      path: '/jobs/new'
      fullPath: '/main/jobs/new'
      preLoaderRoute: typeof AuthenticatedMainJobsNewRouteImport
      parentRoute: typeof AuthenticatedMainRoute
    }
    '/_authenticated/main/clients/$id': {
      id: '/_authenticated/main/clients/$id'
      path: '/$id'
      fullPath: '/main/clients/$id'
      preLoaderRoute: typeof AuthenticatedMainClientsIdRouteImport
      parentRoute: typeof AuthenticatedMainClientsRoute
    }
    '/_authenticated/jobs/$slug/stages': {
      id: '/_authenticated/jobs/$slug/stages'
      path: '/stages'
      fullPath: '/jobs/$slug/stages'
      preLoaderRoute: typeof AuthenticatedJobsSlugStagesRouteImport
      parentRoute: typeof AuthenticatedJobsSlugRoute
    }
    '/_authenticated/jobs/$slug/add-candidate': {
      id: '/_authenticated/jobs/$slug/add-candidate'
      path: '/add-candidate'
      fullPath: '/jobs/$slug/add-candidate'
      preLoaderRoute: typeof AuthenticatedJobsSlugAddCandidateRouteImport
      parentRoute: typeof AuthenticatedJobsSlugRoute
    }
    '/_authenticated/client/jobs/$slug': {
      id: '/_authenticated/client/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/client/jobs/$slug'
      preLoaderRoute: typeof AuthenticatedClientJobsSlugRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/staff/jobs/$slug/stages': {
      id: '/_authenticated/staff/jobs/$slug/stages'
      path: '/stages'
      fullPath: '/staff/jobs/$slug/stages'
      preLoaderRoute: typeof AuthenticatedStaffJobsSlugStagesRouteImport
      parentRoute: typeof AuthenticatedStaffJobsSlugRoute
    }
    '/_authenticated/staff/jobs/$slug/add-candidate': {
      id: '/_authenticated/staff/jobs/$slug/add-candidate'
      path: '/add-candidate'
      fullPath: '/staff/jobs/$slug/add-candidate'
      preLoaderRoute: typeof AuthenticatedStaffJobsSlugAddCandidateRouteImport
      parentRoute: typeof AuthenticatedStaffJobsSlugRoute
    }
  }
}

interface AuthenticatedClientRouteChildren {
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
  AuthenticatedClientJobsSlugRoute: typeof AuthenticatedClientJobsSlugRoute
}

const AuthenticatedClientRouteChildren: AuthenticatedClientRouteChildren = {
  AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
  AuthenticatedClientJobsSlugRoute: AuthenticatedClientJobsSlugRoute,
}

const AuthenticatedClientRouteWithChildren =
  AuthenticatedClientRoute._addFileChildren(AuthenticatedClientRouteChildren)

interface AuthenticatedJobsSlugRouteChildren {
  AuthenticatedJobsSlugAddCandidateRoute: typeof AuthenticatedJobsSlugAddCandidateRoute
  AuthenticatedJobsSlugStagesRoute: typeof AuthenticatedJobsSlugStagesRoute
}

const AuthenticatedJobsSlugRouteChildren: AuthenticatedJobsSlugRouteChildren = {
  AuthenticatedJobsSlugAddCandidateRoute:
    AuthenticatedJobsSlugAddCandidateRoute,
  AuthenticatedJobsSlugStagesRoute: AuthenticatedJobsSlugStagesRoute,
}

const AuthenticatedJobsSlugRouteWithChildren =
  AuthenticatedJobsSlugRoute._addFileChildren(
    AuthenticatedJobsSlugRouteChildren,
  )

interface AuthenticatedJobsRouteChildren {
  AuthenticatedJobsSlugRoute: typeof AuthenticatedJobsSlugRouteWithChildren
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
}

const AuthenticatedJobsRouteChildren: AuthenticatedJobsRouteChildren = {
  AuthenticatedJobsSlugRoute: AuthenticatedJobsSlugRouteWithChildren,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
}

const AuthenticatedJobsRouteWithChildren =
  AuthenticatedJobsRoute._addFileChildren(AuthenticatedJobsRouteChildren)

interface AuthenticatedMainClientsRouteChildren {
  AuthenticatedMainClientsIdRoute: typeof AuthenticatedMainClientsIdRoute
}

const AuthenticatedMainClientsRouteChildren: AuthenticatedMainClientsRouteChildren =
  {
    AuthenticatedMainClientsIdRoute: AuthenticatedMainClientsIdRoute,
  }

const AuthenticatedMainClientsRouteWithChildren =
  AuthenticatedMainClientsRoute._addFileChildren(
    AuthenticatedMainClientsRouteChildren,
  )

interface AuthenticatedMainRouteChildren {
  AuthenticatedMainAdminRoute: typeof AuthenticatedMainAdminRoute
  AuthenticatedMainClientsRoute: typeof AuthenticatedMainClientsRouteWithChildren
  AuthenticatedMainSettingsRoute: typeof AuthenticatedMainSettingsRoute
  AuthenticatedMainIndexRoute: typeof AuthenticatedMainIndexRoute
  AuthenticatedMainJobsNewRoute: typeof AuthenticatedMainJobsNewRoute
}

const AuthenticatedMainRouteChildren: AuthenticatedMainRouteChildren = {
  AuthenticatedMainAdminRoute: AuthenticatedMainAdminRoute,
  AuthenticatedMainClientsRoute: AuthenticatedMainClientsRouteWithChildren,
  AuthenticatedMainSettingsRoute: AuthenticatedMainSettingsRoute,
  AuthenticatedMainIndexRoute: AuthenticatedMainIndexRoute,
  AuthenticatedMainJobsNewRoute: AuthenticatedMainJobsNewRoute,
}

const AuthenticatedMainRouteWithChildren =
  AuthenticatedMainRoute._addFileChildren(AuthenticatedMainRouteChildren)

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalSplatRoute: typeof AuthenticatedPortalSplatRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalSplatRoute: AuthenticatedPortalSplatRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedStaffJobsSlugRouteChildren {
  AuthenticatedStaffJobsSlugAddCandidateRoute: typeof AuthenticatedStaffJobsSlugAddCandidateRoute
  AuthenticatedStaffJobsSlugStagesRoute: typeof AuthenticatedStaffJobsSlugStagesRoute
}

const AuthenticatedStaffJobsSlugRouteChildren: AuthenticatedStaffJobsSlugRouteChildren =
  {
    AuthenticatedStaffJobsSlugAddCandidateRoute:
      AuthenticatedStaffJobsSlugAddCandidateRoute,
    AuthenticatedStaffJobsSlugStagesRoute:
      AuthenticatedStaffJobsSlugStagesRoute,
  }

const AuthenticatedStaffJobsSlugRouteWithChildren =
  AuthenticatedStaffJobsSlugRoute._addFileChildren(
    AuthenticatedStaffJobsSlugRouteChildren,
  )

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffIdRoute: typeof AuthenticatedStaffIdRoute
  AuthenticatedStaffActivityRoute: typeof AuthenticatedStaffActivityRoute
  AuthenticatedStaffCandidatesRoute: typeof AuthenticatedStaffCandidatesRoute
  AuthenticatedStaffShortlistRoute: typeof AuthenticatedStaffShortlistRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
  AuthenticatedStaffJobsSlugRoute: typeof AuthenticatedStaffJobsSlugRouteWithChildren
  AuthenticatedStaffJobsIndexRoute: typeof AuthenticatedStaffJobsIndexRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffIdRoute: AuthenticatedStaffIdRoute,
  AuthenticatedStaffActivityRoute: AuthenticatedStaffActivityRoute,
  AuthenticatedStaffCandidatesRoute: AuthenticatedStaffCandidatesRoute,
  AuthenticatedStaffShortlistRoute: AuthenticatedStaffShortlistRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  AuthenticatedStaffJobsSlugRoute: AuthenticatedStaffJobsSlugRouteWithChildren,
  AuthenticatedStaffJobsIndexRoute: AuthenticatedStaffJobsIndexRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedTalentportalRouteChildren {
  AuthenticatedTalentportalClientsRoute: typeof AuthenticatedTalentportalClientsRoute
  AuthenticatedTalentportalMainRoute: typeof AuthenticatedTalentportalMainRoute
  AuthenticatedTalentportalStaffRoute: typeof AuthenticatedTalentportalStaffRoute
  AuthenticatedTalentportalIndexRoute: typeof AuthenticatedTalentportalIndexRoute
}

const AuthenticatedTalentportalRouteChildren: AuthenticatedTalentportalRouteChildren =
  {
    AuthenticatedTalentportalClientsRoute:
      AuthenticatedTalentportalClientsRoute,
    AuthenticatedTalentportalMainRoute: AuthenticatedTalentportalMainRoute,
    AuthenticatedTalentportalStaffRoute: AuthenticatedTalentportalStaffRoute,
    AuthenticatedTalentportalIndexRoute: AuthenticatedTalentportalIndexRoute,
  }

const AuthenticatedTalentportalRouteWithChildren =
  AuthenticatedTalentportalRoute._addFileChildren(
    AuthenticatedTalentportalRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedClientRoute: typeof AuthenticatedClientRouteWithChildren
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRouteWithChildren
  AuthenticatedMainRoute: typeof AuthenticatedMainRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
  AuthenticatedTalentportalRoute: typeof AuthenticatedTalentportalRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientRoute: AuthenticatedClientRouteWithChildren,
  AuthenticatedJobsRoute: AuthenticatedJobsRouteWithChildren,
  AuthenticatedMainRoute: AuthenticatedMainRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
  AuthenticatedTalentportalRoute: AuthenticatedTalentportalRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApplySlugRoute: ApplySlugRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
