/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplySlugRouteImport } from './routes/apply.$slug'
import { Route as AuthenticatedTalentportalRouteImport } from './routes/_authenticated.talentportal'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated.portal'
import { Route as AuthenticatedTalentportalIndexRouteImport } from './routes/_authenticated.talentportal.index'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated.portal.index'
import { Route as AuthenticatedTalentportalStaffRouteImport } from './routes/_authenticated.talentportal.staff'
import { Route as AuthenticatedTalentportalMainRouteImport } from './routes/_authenticated.talentportal.main'
import { Route as AuthenticatedTalentportalClientRouteImport } from './routes/_authenticated.talentportal.client'
import { Route as AuthenticatedPortalShortlistRouteImport } from './routes/_authenticated.portal.shortlist'
import { Route as AuthenticatedPortalSettingsRouteImport } from './routes/_authenticated.portal.settings'
import { Route as AuthenticatedPortalClientsRouteImport } from './routes/_authenticated.portal.clients'
import { Route as AuthenticatedPortalCandidatesRouteImport } from './routes/_authenticated.portal.candidates'
import { Route as AuthenticatedPortalAdminRouteImport } from './routes/_authenticated.portal.admin'
import { Route as AuthenticatedPortalActivityRouteImport } from './routes/_authenticated.portal.activity'
import { Route as AuthenticatedPortalIdRouteImport } from './routes/_authenticated.portal.$id'
import { Route as AuthenticatedPortalSplatRouteImport } from './routes/_authenticated.portal.$'
import { Route as AuthenticatedPortalJobsIndexRouteImport } from './routes/_authenticated.portal.jobs.index'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedPortalJobsNewRouteImport } from './routes/_authenticated.portal.jobs.new'
import { Route as AuthenticatedPortalJobsSlugRouteImport } from './routes/_authenticated.portal.jobs.$slug'
import { Route as AuthenticatedPortalClientsIdRouteImport } from './routes/_authenticated.portal.clients.$id'
import { Route as AuthenticatedPortalJobsSlugStagesRouteImport } from './routes/_authenticated.portal.jobs.$slug.stages'
import { Route as AuthenticatedPortalJobsSlugAddCandidateRouteImport } from './routes/_authenticated.portal.jobs.$slug.add-candidate'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplySlugRoute = ApplySlugRouteImport.update({
  id: '/apply/$slug',
  path: '/apply/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTalentportalRoute =
  AuthenticatedTalentportalRouteImport.update({
    id: '/talentportal',
    path: '/talentportal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTalentportalIndexRoute =
  AuthenticatedTalentportalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTalentportalRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedTalentportalStaffRoute =
  AuthenticatedTalentportalStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedTalentportalRoute,
  } as any)
const AuthenticatedTalentportalMainRoute =
  AuthenticatedTalentportalMainRouteImport.update({
    id: '/main',
    path: '/main',
    getParentRoute: () => AuthenticatedTalentportalRoute,
  } as any)
const AuthenticatedTalentportalClientRoute =
  AuthenticatedTalentportalClientRouteImport.update({
    id: '/client',
    path: '/client',
    getParentRoute: () => AuthenticatedTalentportalRoute,
  } as any)
const AuthenticatedPortalShortlistRoute =
  AuthenticatedPortalShortlistRouteImport.update({
    id: '/shortlist',
    path: '/shortlist',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalSettingsRoute =
  AuthenticatedPortalSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalClientsRoute =
  AuthenticatedPortalClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalCandidatesRoute =
  AuthenticatedPortalCandidatesRouteImport.update({
    id: '/candidates',
    path: '/candidates',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalAdminRoute =
  AuthenticatedPortalAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalActivityRoute =
  AuthenticatedPortalActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalIdRoute = AuthenticatedPortalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPortalRoute,
} as any)
const AuthenticatedPortalSplatRoute =
  AuthenticatedPortalSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalJobsIndexRoute =
  AuthenticatedPortalJobsIndexRouteImport.update({
    id: '/jobs/',
    path: '/jobs/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalJobsNewRoute =
  AuthenticatedPortalJobsNewRouteImport.update({
    id: '/jobs/new',
    path: '/jobs/new',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalJobsSlugRoute =
  AuthenticatedPortalJobsSlugRouteImport.update({
    id: '/jobs/$slug',
    path: '/jobs/$slug',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalClientsIdRoute =
  AuthenticatedPortalClientsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPortalClientsRoute,
  } as any)
const AuthenticatedPortalJobsSlugStagesRoute =
  AuthenticatedPortalJobsSlugStagesRouteImport.update({
    id: '/stages',
    path: '/stages',
    getParentRoute: () => AuthenticatedPortalJobsSlugRoute,
  } as any)
const AuthenticatedPortalJobsSlugAddCandidateRoute =
  AuthenticatedPortalJobsSlugAddCandidateRouteImport.update({
    id: '/add-candidate',
    path: '/add-candidate',
    getParentRoute: () => AuthenticatedPortalJobsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/talentportal': typeof AuthenticatedTalentportalRouteWithChildren
  '/apply/$slug': typeof ApplySlugRoute
  '/portal/$': typeof AuthenticatedPortalSplatRoute
  '/portal/$id': typeof AuthenticatedPortalIdRoute
  '/portal/activity': typeof AuthenticatedPortalActivityRoute
  '/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/portal/candidates': typeof AuthenticatedPortalCandidatesRoute
  '/portal/clients': typeof AuthenticatedPortalClientsRouteWithChildren
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/portal/shortlist': typeof AuthenticatedPortalShortlistRoute
  '/talentportal/client': typeof AuthenticatedTalentportalClientRoute
  '/talentportal/main': typeof AuthenticatedTalentportalMainRoute
  '/talentportal/staff': typeof AuthenticatedTalentportalStaffRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/talentportal/': typeof AuthenticatedTalentportalIndexRoute
  '/portal/clients/$id': typeof AuthenticatedPortalClientsIdRoute
  '/portal/jobs/$slug': typeof AuthenticatedPortalJobsSlugRouteWithChildren
  '/portal/jobs/new': typeof AuthenticatedPortalJobsNewRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/portal/jobs/': typeof AuthenticatedPortalJobsIndexRoute
  '/portal/jobs/$slug/add-candidate': typeof AuthenticatedPortalJobsSlugAddCandidateRoute
  '/portal/jobs/$slug/stages': typeof AuthenticatedPortalJobsSlugStagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/portal/$': typeof AuthenticatedPortalSplatRoute
  '/portal/$id': typeof AuthenticatedPortalIdRoute
  '/portal/activity': typeof AuthenticatedPortalActivityRoute
  '/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/portal/candidates': typeof AuthenticatedPortalCandidatesRoute
  '/portal/clients': typeof AuthenticatedPortalClientsRouteWithChildren
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/portal/shortlist': typeof AuthenticatedPortalShortlistRoute
  '/talentportal/client': typeof AuthenticatedTalentportalClientRoute
  '/talentportal/main': typeof AuthenticatedTalentportalMainRoute
  '/talentportal/staff': typeof AuthenticatedTalentportalStaffRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/talentportal': typeof AuthenticatedTalentportalIndexRoute
  '/portal/clients/$id': typeof AuthenticatedPortalClientsIdRoute
  '/portal/jobs/$slug': typeof AuthenticatedPortalJobsSlugRouteWithChildren
  '/portal/jobs/new': typeof AuthenticatedPortalJobsNewRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/portal/jobs': typeof AuthenticatedPortalJobsIndexRoute
  '/portal/jobs/$slug/add-candidate': typeof AuthenticatedPortalJobsSlugAddCandidateRoute
  '/portal/jobs/$slug/stages': typeof AuthenticatedPortalJobsSlugStagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/talentportal': typeof AuthenticatedTalentportalRouteWithChildren
  '/apply/$slug': typeof ApplySlugRoute
  '/_authenticated/portal/$': typeof AuthenticatedPortalSplatRoute
  '/_authenticated/portal/$id': typeof AuthenticatedPortalIdRoute
  '/_authenticated/portal/activity': typeof AuthenticatedPortalActivityRoute
  '/_authenticated/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/_authenticated/portal/candidates': typeof AuthenticatedPortalCandidatesRoute
  '/_authenticated/portal/clients': typeof AuthenticatedPortalClientsRouteWithChildren
  '/_authenticated/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/_authenticated/portal/shortlist': typeof AuthenticatedPortalShortlistRoute
  '/_authenticated/talentportal/client': typeof AuthenticatedTalentportalClientRoute
  '/_authenticated/talentportal/main': typeof AuthenticatedTalentportalMainRoute
  '/_authenticated/talentportal/staff': typeof AuthenticatedTalentportalStaffRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/talentportal/': typeof AuthenticatedTalentportalIndexRoute
  '/_authenticated/portal/clients/$id': typeof AuthenticatedPortalClientsIdRoute
  '/_authenticated/portal/jobs/$slug': typeof AuthenticatedPortalJobsSlugRouteWithChildren
  '/_authenticated/portal/jobs/new': typeof AuthenticatedPortalJobsNewRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/_authenticated/portal/jobs/': typeof AuthenticatedPortalJobsIndexRoute
  '/_authenticated/portal/jobs/$slug/add-candidate': typeof AuthenticatedPortalJobsSlugAddCandidateRoute
  '/_authenticated/portal/jobs/$slug/stages': typeof AuthenticatedPortalJobsSlugStagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/portal'
    | '/talentportal'
    | '/apply/$slug'
    | '/portal/$'
    | '/portal/$id'
    | '/portal/activity'
    | '/portal/admin'
    | '/portal/candidates'
    | '/portal/clients'
    | '/portal/settings'
    | '/portal/shortlist'
    | '/talentportal/client'
    | '/talentportal/main'
    | '/talentportal/staff'
    | '/portal/'
    | '/talentportal/'
    | '/portal/clients/$id'
    | '/portal/jobs/$slug'
    | '/portal/jobs/new'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/portal/jobs/'
    | '/portal/jobs/$slug/add-candidate'
    | '/portal/jobs/$slug/stages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/apply/$slug'
    | '/portal/$'
    | '/portal/$id'
    | '/portal/activity'
    | '/portal/admin'
    | '/portal/candidates'
    | '/portal/clients'
    | '/portal/settings'
    | '/portal/shortlist'
    | '/talentportal/client'
    | '/talentportal/main'
    | '/talentportal/staff'
    | '/portal'
    | '/talentportal'
    | '/portal/clients/$id'
    | '/portal/jobs/$slug'
    | '/portal/jobs/new'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/portal/jobs'
    | '/portal/jobs/$slug/add-candidate'
    | '/portal/jobs/$slug/stages'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/unauthorized'
    | '/_authenticated/portal'
    | '/_authenticated/talentportal'
    | '/apply/$slug'
    | '/_authenticated/portal/$'
    | '/_authenticated/portal/$id'
    | '/_authenticated/portal/activity'
    | '/_authenticated/portal/admin'
    | '/_authenticated/portal/candidates'
    | '/_authenticated/portal/clients'
    | '/_authenticated/portal/settings'
    | '/_authenticated/portal/shortlist'
    | '/_authenticated/talentportal/client'
    | '/_authenticated/talentportal/main'
    | '/_authenticated/talentportal/staff'
    | '/_authenticated/portal/'
    | '/_authenticated/talentportal/'
    | '/_authenticated/portal/clients/$id'
    | '/_authenticated/portal/jobs/$slug'
    | '/_authenticated/portal/jobs/new'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/_authenticated/portal/jobs/'
    | '/_authenticated/portal/jobs/$slug/add-candidate'
    | '/_authenticated/portal/jobs/$slug/stages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApplySlugRoute: typeof ApplySlugRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$slug': {
      id: '/apply/$slug'
      path: '/apply/$slug'
      fullPath: '/apply/$slug'
      preLoaderRoute: typeof ApplySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/talentportal': {
      id: '/_authenticated/talentportal'
      path: '/talentportal'
      fullPath: '/talentportal'
      preLoaderRoute: typeof AuthenticatedTalentportalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/talentportal/': {
      id: '/_authenticated/talentportal/'
      path: '/'
      fullPath: '/talentportal/'
      preLoaderRoute: typeof AuthenticatedTalentportalIndexRouteImport
      parentRoute: typeof AuthenticatedTalentportalRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/talentportal/staff': {
      id: '/_authenticated/talentportal/staff'
      path: '/staff'
      fullPath: '/talentportal/staff'
      preLoaderRoute: typeof AuthenticatedTalentportalStaffRouteImport
      parentRoute: typeof AuthenticatedTalentportalRoute
    }
    '/_authenticated/talentportal/main': {
      id: '/_authenticated/talentportal/main'
      path: '/main'
      fullPath: '/talentportal/main'
      preLoaderRoute: typeof AuthenticatedTalentportalMainRouteImport
      parentRoute: typeof AuthenticatedTalentportalRoute
    }
    '/_authenticated/talentportal/client': {
      id: '/_authenticated/talentportal/client'
      path: '/client'
      fullPath: '/talentportal/client'
      preLoaderRoute: typeof AuthenticatedTalentportalClientRouteImport
      parentRoute: typeof AuthenticatedTalentportalRoute
    }
    '/_authenticated/portal/shortlist': {
      id: '/_authenticated/portal/shortlist'
      path: '/shortlist'
      fullPath: '/portal/shortlist'
      preLoaderRoute: typeof AuthenticatedPortalShortlistRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/settings': {
      id: '/_authenticated/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof AuthenticatedPortalSettingsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/clients': {
      id: '/_authenticated/portal/clients'
      path: '/clients'
      fullPath: '/portal/clients'
      preLoaderRoute: typeof AuthenticatedPortalClientsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/candidates': {
      id: '/_authenticated/portal/candidates'
      path: '/candidates'
      fullPath: '/portal/candidates'
      preLoaderRoute: typeof AuthenticatedPortalCandidatesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/admin': {
      id: '/_authenticated/portal/admin'
      path: '/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof AuthenticatedPortalAdminRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/activity': {
      id: '/_authenticated/portal/activity'
      path: '/activity'
      fullPath: '/portal/activity'
      preLoaderRoute: typeof AuthenticatedPortalActivityRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/$id': {
      id: '/_authenticated/portal/$id'
      path: '/$id'
      fullPath: '/portal/$id'
      preLoaderRoute: typeof AuthenticatedPortalIdRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/$': {
      id: '/_authenticated/portal/$'
      path: '/$'
      fullPath: '/portal/$'
      preLoaderRoute: typeof AuthenticatedPortalSplatRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/jobs/': {
      id: '/_authenticated/portal/jobs/'
      path: '/jobs'
      fullPath: '/portal/jobs/'
      preLoaderRoute: typeof AuthenticatedPortalJobsIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/jobs/new': {
      id: '/_authenticated/portal/jobs/new'
      path: '/jobs/new'
      fullPath: '/portal/jobs/new'
      preLoaderRoute: typeof AuthenticatedPortalJobsNewRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/jobs/$slug': {
      id: '/_authenticated/portal/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/portal/jobs/$slug'
      preLoaderRoute: typeof AuthenticatedPortalJobsSlugRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/clients/$id': {
      id: '/_authenticated/portal/clients/$id'
      path: '/$id'
      fullPath: '/portal/clients/$id'
      preLoaderRoute: typeof AuthenticatedPortalClientsIdRouteImport
      parentRoute: typeof AuthenticatedPortalClientsRoute
    }
    '/_authenticated/portal/jobs/$slug/stages': {
      id: '/_authenticated/portal/jobs/$slug/stages'
      path: '/stages'
      fullPath: '/portal/jobs/$slug/stages'
      preLoaderRoute: typeof AuthenticatedPortalJobsSlugStagesRouteImport
      parentRoute: typeof AuthenticatedPortalJobsSlugRoute
    }
    '/_authenticated/portal/jobs/$slug/add-candidate': {
      id: '/_authenticated/portal/jobs/$slug/add-candidate'
      path: '/add-candidate'
      fullPath: '/portal/jobs/$slug/add-candidate'
      preLoaderRoute: typeof AuthenticatedPortalJobsSlugAddCandidateRouteImport
      parentRoute: typeof AuthenticatedPortalJobsSlugRoute
    }
  }
}

interface AuthenticatedPortalClientsRouteChildren {
  AuthenticatedPortalClientsIdRoute: typeof AuthenticatedPortalClientsIdRoute
}

const AuthenticatedPortalClientsRouteChildren: AuthenticatedPortalClientsRouteChildren =
  {
    AuthenticatedPortalClientsIdRoute: AuthenticatedPortalClientsIdRoute,
  }

const AuthenticatedPortalClientsRouteWithChildren =
  AuthenticatedPortalClientsRoute._addFileChildren(
    AuthenticatedPortalClientsRouteChildren,
  )

interface AuthenticatedPortalJobsSlugRouteChildren {
  AuthenticatedPortalJobsSlugAddCandidateRoute: typeof AuthenticatedPortalJobsSlugAddCandidateRoute
  AuthenticatedPortalJobsSlugStagesRoute: typeof AuthenticatedPortalJobsSlugStagesRoute
}

const AuthenticatedPortalJobsSlugRouteChildren: AuthenticatedPortalJobsSlugRouteChildren =
  {
    AuthenticatedPortalJobsSlugAddCandidateRoute:
      AuthenticatedPortalJobsSlugAddCandidateRoute,
    AuthenticatedPortalJobsSlugStagesRoute:
      AuthenticatedPortalJobsSlugStagesRoute,
  }

const AuthenticatedPortalJobsSlugRouteWithChildren =
  AuthenticatedPortalJobsSlugRoute._addFileChildren(
    AuthenticatedPortalJobsSlugRouteChildren,
  )

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalSplatRoute: typeof AuthenticatedPortalSplatRoute
  AuthenticatedPortalIdRoute: typeof AuthenticatedPortalIdRoute
  AuthenticatedPortalActivityRoute: typeof AuthenticatedPortalActivityRoute
  AuthenticatedPortalAdminRoute: typeof AuthenticatedPortalAdminRoute
  AuthenticatedPortalCandidatesRoute: typeof AuthenticatedPortalCandidatesRoute
  AuthenticatedPortalClientsRoute: typeof AuthenticatedPortalClientsRouteWithChildren
  AuthenticatedPortalSettingsRoute: typeof AuthenticatedPortalSettingsRoute
  AuthenticatedPortalShortlistRoute: typeof AuthenticatedPortalShortlistRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedPortalJobsSlugRoute: typeof AuthenticatedPortalJobsSlugRouteWithChildren
  AuthenticatedPortalJobsNewRoute: typeof AuthenticatedPortalJobsNewRoute
  AuthenticatedPortalJobsIndexRoute: typeof AuthenticatedPortalJobsIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalSplatRoute: AuthenticatedPortalSplatRoute,
  AuthenticatedPortalIdRoute: AuthenticatedPortalIdRoute,
  AuthenticatedPortalActivityRoute: AuthenticatedPortalActivityRoute,
  AuthenticatedPortalAdminRoute: AuthenticatedPortalAdminRoute,
  AuthenticatedPortalCandidatesRoute: AuthenticatedPortalCandidatesRoute,
  AuthenticatedPortalClientsRoute: AuthenticatedPortalClientsRouteWithChildren,
  AuthenticatedPortalSettingsRoute: AuthenticatedPortalSettingsRoute,
  AuthenticatedPortalShortlistRoute: AuthenticatedPortalShortlistRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedPortalJobsSlugRoute:
    AuthenticatedPortalJobsSlugRouteWithChildren,
  AuthenticatedPortalJobsNewRoute: AuthenticatedPortalJobsNewRoute,
  AuthenticatedPortalJobsIndexRoute: AuthenticatedPortalJobsIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedTalentportalRouteChildren {
  AuthenticatedTalentportalClientRoute: typeof AuthenticatedTalentportalClientRoute
  AuthenticatedTalentportalMainRoute: typeof AuthenticatedTalentportalMainRoute
  AuthenticatedTalentportalStaffRoute: typeof AuthenticatedTalentportalStaffRoute
  AuthenticatedTalentportalIndexRoute: typeof AuthenticatedTalentportalIndexRoute
}

const AuthenticatedTalentportalRouteChildren: AuthenticatedTalentportalRouteChildren =
  {
    AuthenticatedTalentportalClientRoute: AuthenticatedTalentportalClientRoute,
    AuthenticatedTalentportalMainRoute: AuthenticatedTalentportalMainRoute,
    AuthenticatedTalentportalStaffRoute: AuthenticatedTalentportalStaffRoute,
    AuthenticatedTalentportalIndexRoute: AuthenticatedTalentportalIndexRoute,
  }

const AuthenticatedTalentportalRouteWithChildren =
  AuthenticatedTalentportalRoute._addFileChildren(
    AuthenticatedTalentportalRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedTalentportalRoute: typeof AuthenticatedTalentportalRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedTalentportalRoute: AuthenticatedTalentportalRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApplySlugRoute: ApplySlugRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
